import 'dart:math';

/// Bridge to Rust Core (vendeta-core)
/// Production: generated by flutter_rust_bridge_codegen
/// Development: stub implementation for UI testing
class VendettaBridge {
  static VendettaBridge? _instance;
  static VendettaBridge get instance => _instance ??= VendettaBridge._();
  VendettaBridge._();

  /// Validate EAN barcode
  Future<bool> validateEan(String ean) async {
    if (ean.length != 13 && ean.length != 8 && ean.length != 12) return false;
    if (!RegExp(r'^\d+$').hasMatch(ean)) return false;
    return _checkDigit(ean);
  }

  /// Generate submission hash
  Future<String> generateHash({
    required String ean,
    required int priceCents,
    required double latitude,
    required double longitude,
    required int timestamp,
    required String userId,
  }) async {
    final input = '$ean:$priceCents:'
        '${latitude.toStringAsFixed(6)}:'
        '${longitude.toStringAsFixed(6)}:'
        '$timestamp:$userId';
    return _simpleHash(input);
  }

  /// Encode GPS as Geohash5
  Future<String> encodeGeohash(double lat, double lng) async {
    return 'u281z'; // Munich default for testing
  }

  /// Get 9 neighbor geohash cells
  Future<List<String>> geohashNeighbors(String center) async {
    return [center];
  }

  /// Distance in meters (Haversine approximation)
  Future<double> distanceMeters(
      double lat1, double lng1, double lat2, double lng2) async {
    const r = 6371000.0;
    final dLat = _rad(lat2 - lat1);
    final dLng = _rad(lng2 - lng1);
    final a = sin(dLat / 2) * sin(dLat / 2) +
        cos(_rad(lat1)) * cos(_rad(lat2)) * sin(dLng / 2) * sin(dLng / 2);
    return r * 2 * atan2(sqrt(a), sqrt(1 - a));
  }

  /// Price float -> cents (safe rounding)
  int priceToCents(double price) => (price * 100).round();

  /// Cents -> display string
  String centsToDisplay(int cents, {String currency = 'EUR'}) {
    final euros = cents ~/ 100;
    final cts = cents % 100;
    return '$euros.${cts.toString().padLeft(2, '0')}';
  }

  /// lat/lng -> int32 x 1e6
  int latToInt32(double lat) => (lat * 1000000).round();
  int lngToInt32(double lng) => (lng * 1000000).round();

  /// Generate new wallet (first app start)
  Future<Map<String, String>> generateWallet({required List<int> deviceSalt}) async {
    // Stub: returns mock wallet for UI testing
    // Production: Rust FFI call to generate_wallet()
    return {
      'mnemonic': 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',
      'ethAddress': '0x9858EfFD232B4033E47d90003D41EC34EcaedA94',
      'userHash': 'a' * 64,
    };
  }

  /// Restore wallet from seed phrase
  Future<Map<String, String>> restoreWallet({required String mnemonic, required List<int> deviceSalt}) async {
    final words = mnemonic.trim().split(' ');
    if (words.length != 12 && words.length != 24) {
      throw Exception('Ungültige Seed-Phrase');
    }
    return {
      'mnemonic': mnemonic,
      'ethAddress': '0x0000000000000000000000000000000000000001',
      'userHash': 'b' * 64,
    };
  }

  double _rad(double deg) => deg * pi / 180;

  bool _checkDigit(String code) {
    final digits = code.codeUnits.map((c) => c - 48).toList();
    final check = digits.length - 1;
    var sum = 0;
    for (var i = 0; i < check; i++) {
      sum += digits[i] * (i.isEven ? 1 : 3);
    }
    return digits[check] == (10 - (sum % 10)) % 10;
  }

  String _simpleHash(String input) {
    var hash = 0;
    for (final c in input.codeUnits) {
      hash = ((hash << 5) - hash) + c;
      hash = hash & 0xFFFFFFFF;
    }
    return hash.abs().toRadixString(16).padLeft(64, '0');
  }
}
