import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

/// Bridge to Rust Core (vendeta-core)
/// Production: generated by flutter_rust_bridge_codegen
/// Development: stub implementation for UI testing
class VendettaBridge {
  static VendettaBridge? _instance;
  static VendettaBridge get instance => _instance ??= VendettaBridge._();
  VendettaBridge._();

  /// Validate EAN barcode (matches Rust: EanCode::parse accepts 8 or 13)
  Future<bool> validateEan(String ean) async {
    if (ean.length != 13 && ean.length != 8) return false;
    if (!RegExp(r'^\d+$').hasMatch(ean)) return false;
    return _checkDigit(ean);
  }

  /// Generate submission hash — SHA-256, binary format matching Rust core hash.rs
  /// Format: SHA256(ean_bytes | price_le64 | lat6_le32 | lng6_le32 | ts_le64 | user_bytes)
  Future<String> generateHash({
    required String ean,
    required int priceCents,
    required double latitude,
    required double longitude,
    required int timestamp,
    required String userId,
  }) async {
    final lat6 = (latitude * 1000000).round();
    final lng6 = (longitude * 1000000).round();

    final builder = BytesBuilder();
    builder.add(utf8.encode(ean));
    builder.add(_uint64LE(priceCents));
    builder.add(_int32LE(lat6));
    builder.add(_int32LE(lng6));
    builder.add(_uint64LE(timestamp));
    builder.add(utf8.encode(userId));

    final hash = sha256.convert(builder.toBytes());
    return hash.toString(); // 64 hex chars, matches Rust SubmissionHash::to_hex()
  }

  /// Encode GPS as Geohash5
  Future<String> encodeGeohash(double lat, double lng) async {
    return 'u281z'; // Munich default for testing
  }

  /// Get 9 neighbor geohash cells
  Future<List<String>> geohashNeighbors(String center) async {
    return [center];
  }

  /// Distance in meters (Haversine approximation)
  Future<double> distanceMeters(
      double lat1, double lng1, double lat2, double lng2) async {
    const r = 6371000.0;
    final dLat = _rad(lat2 - lat1);
    final dLng = _rad(lng2 - lng1);
    final a = sin(dLat / 2) * sin(dLat / 2) +
        cos(_rad(lat1)) * cos(_rad(lat2)) * sin(dLng / 2) * sin(dLng / 2);
    return r * 2 * atan2(sqrt(a), sqrt(1 - a));
  }

  /// Price float -> cents (safe rounding)
  int priceToCents(double price) => (price * 100).round();

  /// Cents -> display string
  String centsToDisplay(int cents, {String currency = 'EUR'}) {
    final euros = cents ~/ 100;
    final cts = cents % 100;
    return '$euros.${cts.toString().padLeft(2, '0')}';
  }

  /// lat/lng -> int32 x 1e6
  int latToInt32(double lat) => (lat * 1000000).round();
  int lngToInt32(double lng) => (lng * 1000000).round();

  /// Generate new wallet (first app start)
  Future<Map<String, String>> generateWallet({required List<int> deviceSalt}) async {
    // Stub: returns mock wallet for UI testing
    // Production: Rust FFI call to generate_wallet()
    return {
      'mnemonic': 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',
      'ethAddress': '0x9858EfFD232B4033E47d90003D41EC34EcaedA94',
      'userHash': 'a' * 64,
    };
  }

  /// Restore wallet from seed phrase
  Future<Map<String, String>> restoreWallet({required String mnemonic, required List<int> deviceSalt}) async {
    final words = mnemonic.trim().split(' ');
    if (words.length != 12 && words.length != 24) {
      throw Exception('Ungültige Seed-Phrase');
    }
    return {
      'mnemonic': mnemonic,
      'ethAddress': '0x0000000000000000000000000000000000000001',
      'userHash': 'b' * 64,
    };
  }

  double _rad(double deg) => deg * pi / 180;

  bool _checkDigit(String code) {
    final digits = code.codeUnits.map((c) => c - 48).toList();
    final check = digits.length - 1;
    var sum = 0;
    for (var i = 0; i < check; i++) {
      sum += digits[i] * (i.isEven ? 1 : 3);
    }
    return digits[check] == (10 - (sum % 10)) % 10;
  }

  Uint8List _uint64LE(int value) {
    final data = ByteData(8);
    data.setUint64(0, value, Endian.little);
    return data.buffer.asUint8List();
  }

  Uint8List _int32LE(int value) {
    final data = ByteData(4);
    data.setInt32(0, value, Endian.little);
    return data.buffer.asUint8List();
  }
}
